### ISSUE TITLE
Add operator in discord bot syntax to range parameter values over the number of samples

### ISSUE THREAD

**Issue by parlance-zz** [parlance-zz/g-diffuser-lib#16]
command param ranges with : operator

distributes reps over the defined (multi-dimensional if more than 1) param space ranges

**Comment by lootsorrow** [comment]
lootsorrow liked this post

**Comment by parlance-zz** [comment]
Closing as duplicate, moved to https://github.com/parlance-zz/g-diffuser-lib/issues/59
