### ISSUE TITLE
[enhancement] RAM management

### ISSUE THREAD

**Issue by Ma5onic** [parlance-zz/g-diffuser-lib#22]
I noticed that 4 pipelines are loaded when the bots starts.
Namely: `diffuser`, `txt2img`, `img2img`,  `img_inp`
Using the optimized mode, it took around 8.5 GB of Memory to load the bot.

![image](https://user-images.githubusercontent.com/18509613/191629874-ab002fe0-47bc-49b8-954d-7fb2ba33da1e.png)

possible solution:
```python
import gc
example_model = ExampleModel().cuda()

del example_model

gc.collect()
# The model will normally stay on the cache until something takes it's place
torch.cuda.empty_cache()
```
https://gist.github.com/ejmejm/1baeddbbe48f58dbced9c019c25ebf71

**Comment by Ma5onic** [comment]
Since the queue executes commands sequentially, wouldn't it be more efficient to load models on-demand? That way people with a GPU with <8GB RAM in their GPU can load the bot.

**Comment by parlance-zz** [comment]
The beta2 branch already reduces this down to just 2 pipelines as the inpainting pipeline is a superset of the functionality built into img2img. Technically, it is also a superset of the functionality of the txt2img pipeline and I intend to reduce the number of pipes down to just 1, at least until diffusers can get their act together with memory usage.

I am leaving this issue open to track the progress. Thank you.

**Comment by parlance-zz** [comment]
I should also mention: 

The model load time is very significant and can easily quadruple the generation time if you need to reload the model for each command. The workaround in beta2 is a) reducing the number of required pipes, and b) you can use the CLI to do single generation commands one at a time, and this will only use whatever model you need to actually complete your command, very similar to how the old CompVis code worked.

Lastly, in beta2 you have the option of using a pre-specified sub-selection of pipes in the config file, allowing to save memory if you choose to forego the functionality in other pipes. This will be important when more models / pipes are added to diffusers.

**Comment by parlance-zz** [comment]
This is now complete with the integration of haffried's grpc server in the dev branch.
